# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- event-grid

pool: Harshit-pool

steps:

- script: terraform init
  displayName: 'Terraform init'

- script: terraform plan 
  displayName: 'Terraform plan'
  
- script: terraform apply -auto-approve
  displayName: 'Terraform apply'

